name: Deploy Cloud Functions
on:
  # 手動ormainブランチにpush時に実行
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-job:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/161988452667/locations/global/workloadIdentityPools/github/providers/gitHub'
          service_account: 'albem-dev-github-actions@albem-dev.iam.gserviceaccount.com'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 379.0.0'
      - name: 'Upload test file'
        run: 'echo "test" > test.txt && gsutil cp test.txt gs://albem-script-dev'

    # steps:
    #   # ソースコードのチェックアウトをする
    # - uses: 'actions/checkout@v3'

    # - id: 'auth'
    #   name: 'Authenticate to Google Cloud'
    #   # Workload Identity連携を利用してGitHub ActionsからGoogle Cloudへ認証を行う
    #   uses: 'google-github-actions/auth@v1'
    #   with:
    #     workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
    #     service_account: gha-cloudfunctions-deploy@${{ vars.PROJECT_ID }}.iam.gserviceaccount.com

    # - name: 'Set up Cloud SDK'
    #   # gcloudコマンドを実行するためにCloud SDKを準備する
    #   uses: 'google-github-actions/setup-gcloud@v1'

    # - name: 'Deploy Cloud Functions gen2 Using gcloud command'
    #   # gcloudコマンドを利用してCloud Functionsをデプロイする
    #   run: >-
    #     gcloud functions deploy ${{ vars.CLOUD_FUNCTIONS_ID }}
    #     --runtime=python310
    #     --region=asia-northeast1
    #     --source=./
    #     --entry-point=Cloud Functionsで利用するエントリーポイント
    #     --trigger-http
    #     --no-allow-unauthenticated
    #     --set-env-vars GCP_PROJECT=${{ vars.PROJECT_ID }}
    #     --run-service-account 事前に作っておいたCloud FunctionsのランタイムサービスアカウントID@${{ vars.PROJECT_ID }}.iam.gserviceaccount.com
